export const BUILDING_DETAILS_REQUEST = 'BUILDING_DETAILS_REQUEST';
export const BUILDING_DETAILS_SUCCESS = 'BUILDING_DETAILS_SUCCESS';
export const BUILDING_DETAILS_FAIL = 'BUILDING_DETAILS_FAIL';

export const BUILDING_MANAGED_REQUEST = 'BUILDING_MANAGED_REQUEST';
export const BUILDING_MANAGED_SUCCESS = 'BUILDING_MANAGED_SUCCESS';
export const BUILDING_MANAGED_FAIL = 'BUILDING_MANAGED_FAIL';

export const BUILDING_DELETED_REQUEST = 'BUILDING_DELETED_REQUEST';
export const BUILDING_DELETED_SUCCESS = 'BUILDING_DELETED_SUCCESS';
export const BUILDING_DELETED_FAIL = 'BUILDING_DELETED_FAIL';

export const BUILDING_ADDED_REQUEST = 'BUILDING_ADDED_REQUEST';
export const BUILDING_ADDED_SUCCESS = 'BUILDING_ADDED_SUCCESS';
export const BUILDING_ADDED_FAIL = 'BUILDING_ADDED_FAIL';

export const BUILDING_EDITED_REQUEST = 'BUILDING_EDITED_REQUEST';
export const BUILDING_EDITED_SUCCESS = 'BUILDING_EDITED_SUCCESS';
export const BUILDING_EDITED_FAIL = 'BUILDING_EDITED_FAIL';
