export const CAMERA_DETAILS_REQUEST = 'CAMERA_DETAILS_REQUEST';
export const CAMERA_DETAILS_SUCCESS = 'CAMERA_DETAILS_SUCCESS';
export const CAMERA_DETAILS_FAIL = 'CAMERA_DETAILS_FAIL';

export const CAMERA_DELETED_REQUEST = 'CAMERA_DELETED_REQUEST';
export const CAMERA_DELETED_SUCCESS = 'CAMERA_DELETED_SUCCESS';
export const CAMERA_DELETED_FAIL = 'CAMERA_DELETED_FAIL';

export const CAMERA_ADDED_REQUEST = 'CAMERA_ADDED_REQUEST';
export const CAMERA_ADDED_SUCCESS = 'CAMERA_ADDED_SUCCESS';
export const CAMERA_ADDED_FAIL = 'CAMERA_ADDED_FAIL';

export const CAMERA_EDITED_REQUEST = 'CAMERA_EDITED_REQUEST';
export const CAMERA_EDITED_SUCCESS = 'CAMERA_EDITED_SUCCESS';
export const CAMERA_EDITED_FAIL = 'CAMERA_EDITED_FAIL';
