export const PERSON_DETAILS_REQUEST = 'PERSON_DETAILS_REQUEST';
export const PERSON_DETAILS_SUCCESS = 'PERSON_DETAILS_SUCCESS';
export const PERSON_DETAILS_FAIL = 'PERSON_DETAILS_FAIL';

export const PERSON_REGISTER_REQUEST = 'PERSON_REGISTER_REQUEST';
export const PERSON_REGISTER_SUCCESS = 'PERSON_REGISTER_SUCCESS';
export const PERSON_REGISTER_FAIL = 'PERSON_REGISTER_FAIL';

export const PERSON_DELETED_REQUEST = 'PERSON_DELETED_REQUEST';
export const PERSON_DELETED_SUCCESS = 'PERSON_DELETED_SUCCESS';
export const PERSON_DELETED_FAIL = 'PERSON_DELETED_FAIL';

export const PERSON_ADDED_REQUEST = 'PERSON_ADDED_REQUEST';
export const PERSON_ADDED_SUCCESS = 'PERSON_ADDED_SUCCESS';
export const PERSON_ADDED_FAIL = 'PERSON_ADDED_FAIL';
