export const TURN_DETAILS_REQUEST = 'TURN_DETAILS_REQUEST';
export const TURN_DETAILS_SUCCESS = 'TURN_DETAILS_SUCCESS';
export const TURN_DETAILS_FAIL = 'TURN_DETAILS_FAIL';

export const TURN_STATS_REQUEST = 'TURN_STATS_REQUEST';
export const TURN_STATS_SUCCESS = 'TURN_STATS_SUCCESS';
export const TURN_STATS_FAIL = 'TURN_STATS_FAIL';
