export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_INFO_UPDATED_REQUEST = 'USER_INFO_UPDATED_REQUEST';
export const USER_INFO_UPDATED_SUCCESS = 'USER_INFO_UPDATED_SUCCESS';
export const USER_INFO_UPDATED_FAIL = 'USER_INFO_UPDATED_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_CHANGE_REQUEST = 'USER_CHANGE_REQUEST';
export const USER_CHANGE_SUCCESS = 'USER_CHANGE_SUCCESS';
export const USER_CHANGE_FAIL = 'USER_CHANGE_FAIL';

export const USER_ADDED_REQUEST = 'USER_ADDED_REQUEST';
export const USER_ADDED_SUCCESS = 'USER_ADDED_SUCCESS';
export const USER_ADDED_FAIL = 'USER_ADDED_FAIL';

export const USER_EDITED_REQUEST = 'USER_EDITED_REQUEST';
export const USER_EDITED_SUCCESS = 'USER_EDITED_SUCCESS';
export const USER_EDITED_FAIL = 'USER_EDITED_FAIL';

export const USER_DELETED_REQUEST = 'USER_DELETED_REQUEST';
export const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
export const USER_DELETED_FAIL = 'USER_DELETED_FAIL';
